# Generated by Django 5.2.4 on 2025-08-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='code',
            field=models.CharField(max_length=7),
        ),
    ]
